# Generated by Django 2.1 on 2019-10-03 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('context_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('tags', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=300, null=True)),
                ('imgSrc', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=10, null=True)),
                ('updateTime', models.CharField(max_length=100, null=True)),
                ('latestChapter', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='novel_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Novel'),
        ),
    ]
