# Generated by Django 2.1 on 2019-10-04 17:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='novel',
            name='updateTimeOnServer',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 4, 17, 13, 5, 929367, tzinfo=utc)),
        ),
    ]
