# Generated by Django 2.1 on 2019-10-03 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='biqugePath',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
