# Generated by Django 2.1 on 2019-10-04 17:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20191005_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='novel',
            name='updateTimeOnServer',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 4, 17, 24, 25, 810044, tzinfo=utc)),
        ),
    ]
